apiVersion: v2
appVersion: 5.1.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: peertube helm chart
home: https://gitlab.metaways.net/se/peertube
maintainers:
  - name: Metaways Infosystems GmbH
    url: https://www.metaways.de/
name: peertube
version: 0.1.0