{{- if (include "peertube.database.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peertube.database.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
stringData:
  username: {{ .Values.peertube.database.username }}
  password: {{ .Values.peertube.database.password }}
{{- end }}