workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

stages:
  - package

include:
  - component: $CI_SERVER_FQDN/gitlabci-components/helm-build/build@1.2.0
    inputs:
      name: peertube