.build:
  stage: build
  image: alpine/helm
  variables:
    CHART_VERSION: ""
  before_script:
    - helm registry login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - 'sed -i "/^version:/c\version: ${CHART_VERSION}" chart/Chart.yaml'
    - helm dependency build chart
    - helm package chart
    - helm push peertube-*.tgz oci://${CI_REGISTRY_IMAGE}

build:
  extends: .build
  variables:
    CHART_VERSION: ${CI_COMMIT_TAG}
  rules:
    - if: $CI_COMMIT_TAG